"""empty message

Revision ID: 1788559dad60
Revises: c7d36d40e685
Create Date: 2022-09-07 21:32:15.609543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1788559dad60'
down_revision = 'c7d36d40e685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('numberrelationmessage', sa.Column('device_id', sa.Integer(), nullable=True))
    op.drop_column('numberrelationmessage', 'number_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('numberrelationmessage', sa.Column('number_id', sa.INTEGER(), nullable=True))
    op.drop_column('numberrelationmessage', 'device_id')
    # ### end Alembic commands ###
