"""empty message

Revision ID: d92c22711ab4
Revises: ecd33954bdf7
Create Date: 2022-08-29 15:18:52.874149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92c22711ab4'
down_revision = 'ecd33954bdf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('numbers', sa.Column('number_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('numbers', 'number_type')
    # ### end Alembic commands ###
