"""empty message

Revision ID: ecd33954bdf7
Revises: 
Create Date: 2022-08-29 15:09:33.416507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd33954bdf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('devices_name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('partitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('partition', sa.String(length=20), nullable=True),
    sa.Column('devices_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['devices_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('numbers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('partition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partition_id'], ['partitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recv_from_number', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.String(length=500), nullable=True),
    sa.Column('recv_time', sa.DateTime(), nullable=True),
    sa.Column('numbers_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['numbers_id'], ['numbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('numbers')
    op.drop_table('partitions')
    op.drop_table('users')
    op.drop_table('devices')
    # ### end Alembic commands ###
